In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
import numpy as np

In [53]:
np.__version__

'1.26.4'

In [2]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [4]:
arr.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
arr.reshape(5,2)[2,1]

6

In [5]:
arr.reshape(5,2)[:2]

array([[1, 2],
       [3, 4]])

In [8]:
arr.sum()

55

In [11]:
arr.argmin()

0

In [12]:
arr.argmax()

9

In [13]:
arr.min()

1

In [14]:
arr.max()

10

In [15]:
arr.mean()

5.5

In [24]:
np.median(arr)

5.5

In [25]:
arr= np.arange(1,11)
arr1=[x+5 for x in arr]
arr2=[[arr],[arr1]]
arr2

[[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])],
 [[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]]

In [8]:
array=[1,2,2,3,4,4]
uniq=np.unique(array)
uniq

array([1, 2, 3, 4])

In [9]:
array=[3,1,2]
sort=np.sort(array)
sort

array([1, 2, 3])

In [21]:
array1=[1,2]
array2=[3,4]
array=np.concatenate((array1,array2))
array

array([1, 2, 3, 4])

In [23]:
np.vstack((array1,array2))

array([[1, 2],
       [3, 4]])

In [24]:
np.transpose((array1,array2))

array([[1, 3],
       [2, 4]])

In [25]:
np.dot(array1,array2)

11

In [53]:
arr=np.random.rand(5)
arr

array([0.37704126, 0.69657723, 0.21760099, 0.85346239, 0.23490287])

In [56]:
np.random.randn(5)

array([-0.3068131 , -1.01476727,  0.74740992, -0.96368389,  0.57392125])

In [73]:
array=np.array([1,2,3,4,5,6])
reshape=array.reshape(2,3)
reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
greater5=array >5
greater5
# mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
array =np.array([1,2,3])
square=np.array([x**2 for x in array])
square

array([1, 4, 9])

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.add(arr1,arr2)
# element-wise

array([5, 7, 9])

In [6]:
arr=np.array([1,2,3,4,3])
indices= np.where(arr==3)
indices

(array([2, 4]),)

In [7]:
arr1= np.array([1,2,3])
arr2=np.array([2,3,4])
np.intersect1d(arr1,arr2)


array([2, 3])

In [9]:
arr= np.array([1,2,3,4,5])
np.std(arr)
# standerd deviation

1.4142135623730951

In [17]:
arr=np.array([1,2,3])
np.save(('my arr'),arr)


In [20]:
np.load(('my arr'),arr)

FileNotFoundError: [Errno 2] No such file or directory: 'my arr'

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
arr=np.array([10,20,30,40,50])
arr[1:3]

array([20, 30])

In [22]:
arr=np.array([5,7,2,9,3])
arr.max()

9

In [23]:
arr.min()

2

In [24]:
arr=np.array([1,2,3,4])
arr.sum()

10

In [25]:
arr.mean()

2.5

In [31]:
arr=np.array([[1,2],[3,4]])
arr.flatten()

array([1, 2, 3, 4])

In [33]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [45]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [46]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [73]:
arr=np.array([10,20,30,40,50])
indices=np.array([1,3])
result=arr[indices]
result

array([20, 40])

In [76]:
arr=np.array([10,20,30,40,50,60])
arr.reshape((2,3))

array([[10, 20, 30],
       [40, 50, 60]])

In [77]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=(arr1)*(arr2)
arr

array([ 4, 10, 18])

In [81]:
arr=np.array([1,2,3])
arr1=np.array([x*10 for x in arr])
arr1

array([10, 20, 30])

In [7]:
arr=np.array([1,2,2,3,4])
np.count_nonzero(arr==2)
# count the occurance of value

2